<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="1" tests="3" time="0.255" timestamp="2024-01-26T09:22:11.241143" hostname="CWRPC497"><testcase classname="test_compare" name="test_greater" time="0.002"><failure message="assert 100 &gt; 100">@pytest.mark.great
    def test_greater():
        num = 100
&gt;       assert num &gt; 100
E       assert 100 &gt; 100

test_compare.py:6: AssertionError</failure></testcase><testcase classname="test_compare" name="test_greater_equal" time="0.001"><skipped type="pytest.skip" message="unconditional skip">D:\MyGitHub\Python_Diehl_Training\test\test_compare.py:8: unconditional skip</skipped></testcase><testcase classname="test_compare" name="test_less" time="0.001"><failure message="assert 100 &lt; 100">@pytest.mark.other
    def test_less():
        num = 100
&gt;       assert num &lt; 100
E       assert 100 &lt; 100

test_compare.py:17: AssertionError</failure></testcase></testsuite></testsuites>